CREATE TABLE IF NOT EXISTS words (word TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS games (
 id TEXT PRIMARY KEY,
 state TEXT NOT NULL,
 revision INTEGER NOT NULL DEFAULT 0,
 host_hash TEXT NOT NULL,
 spy_hash TEXT NOT NULL,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
